development: &development
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: rubyup_development
  pool: 5
  username: postgres
  password: password
  
test: &test
  database: rubyup_test
  <<: *development
  
cucumber:
  <<: *test
  
production:
  database: rubyup_production
  <<: *development