<% application_name = "skeleton" %>
development: &development
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= application_name %>_development
  pool: 5
  username: postgres
  password: password
  
test: &test
  database: <%= application_name %>_test
  <<: *development
  
cucumber:
  <<: *test
  
production:
  database: <%= application_name %>_production
  <<: *development